
all: compile execute

compile:
	@echo ----------compilando arquivos----------
	@javac Ball.java
	@echo Ball.java compilado com êxito.
	@javac Player.java
	@echo Player.java compilado com êxito.
	@javac Score.java
	@echo Score.java compilado com êxito.
	@echo

execute:
	@echo ------------execução------------
	@echo iniciando Pong!
	@java Pong
	@echo execução encerrada.
